package com.nsg.domain

/**
 * Created by lijc on 16/3/30.
 */
enum class PropsItemType(val type: String, val desciption: String, val effectTime: String, val imgUrl: String) {

    SupplementaryCard("SupplementaryCard",
            "补签卡", "",
            "http://static-csl.9h-sports.com/prop/2016/qiandaoka.png"),
    BadgeCardGuoAn("BadgeCardGuoAn",
            "北京国安", "30天",
            "http://static-csl.9h-sports.com/prop/2016/guoan.png"),
    BadgeCardShenHua("BadgeCardShenHua",
            "上海申花", "30天",
            "http://static-csl.9h-sports.com/prop/2016/shenhua.png"),
    BadgeCardLiFan("BadgeCardLiFan",
            "重庆力帆", "30天",
            "http://static-csl.9h-sports.com/prop/2016/chongqinglifan.png"),
    BadgeCardFuLi("BadgeCardFuLi",
            "广州富力", "30天",
            "http://static-csl.9h-sports.com/prop/2016/guozhoufuli.png"),
    BadgeCardHengDa("BadgeCardHengDa",
            "广州恒大", "30天",
            "http://static-csl.9h-sports.com/prop/2016/guozhouhengda.png"),
    BadgeCardHuaXiaXingFu("BadgeCardHuaXiaXingFu",
            "河北华夏幸福", "30天",
            "http://static-csl.9h-sports.com/prop/2016/hebei.png"),
    BadgeCardJianYe("BadgeCardJianYe",
            "河南建业", "30天",
            "http://static-csl.9h-sports.com/prop/2016/henanjianye.png"),
    BadgeCardSuNing("BadgeCardSuNing",
            "江苏苏宁", "30天",
            "http://static-csl.9h-sports.com/prop/2016/jiangsusuning.png"),
    BadgeCardHengYuan("BadgeCardHengYuan",
            "辽宁宏远", "30天",
            "http://static-csl.9h-sports.com/prop/2016/liaoninghongyuan.png"),
    BadgeCardLvCheng("BadgeCardLvCheng",
            "杭州绿城", "30天",
            "http://static-csl.9h-sports.com/prop/2016/lvcheng.png"),
    BadgeCardLuNeng("BadgeCardLuNeng",
            "山东鲁能", "30天",
            "http://static-csl.9h-sports.com/prop/2016/shandongluneng.png"),
    BadgeCardShangGang("BadgeCardShangGang",
            "上海上港", "30天",
            "http://static-csl.9h-sports.com/prop/2016/shanggang.png"),
    BadgeCardTaiDa("BadgeCardTaiDa",
            "天津泰达", "30天",
            "http://static-csl.9h-sports.com/prop/2016/taida.png"),
    BadgeCardYaTai("BadgeCardYaTai",
            "长春亚泰", "30天",
            "http://static-csl.9h-sports.com/prop/2016/yatai.png"),
    BadgeCardYanBian("BadgeCardYanBian",
            "延边长白山", "30天",
            "http://static-csl.9h-sports.com/prop/2016/yanbian.png"),
    BadgeCardYongChang("BadgeCardYongChang",
            "石家庄永昌", "30天",
            "http://static-csl.9h-sports.com/prop/2016/yongchang.png"),
    BadgeCardGuoAn60("BadgeCardGuoAn60",
            "北京国安", "60天",
            "http://static-csl.9h-sports.com/prop/2016/guoan.png"),
    BadgeCardShenHua60("BadgeCardShenHua60",
            "上海申花", "60天",
            "http://static-csl.9h-sports.com/prop/2016/shenhua.png"),
    BadgeCardLiFan60("BadgeCardLiFan60",
            "重庆力帆", "60天",
            "http://static-csl.9h-sports.com/prop/2016/chongqinglifan.png"),
    BadgeCardFuLi60("BadgeCardFuLi60",
            "广州富力", "60天",
            "http://static-csl.9h-sports.com/prop/2016/guozhoufuli.png"),
    BadgeCardHengDa60("BadgeCardHengDa60",
            "广州恒大", "60天",
            "http://static-csl.9h-sports.com/prop/2016/guozhouhengda.png"),
    BadgeCardHuaXiaXingFu60("BadgeCardHuaXiaXingFu60",
            "河北华夏幸福", "60天",
            "http://static-csl.9h-sports.com/prop/2016/hebei.png"),
    BadgeCardJianYe60("BadgeCardJianYe60",
            "河南建业", "60天",
            "http://static-csl.9h-sports.com/prop/2016/henanjianye.png"),
    BadgeCardSuNing60("BadgeCardSuNing60",
            "江苏苏宁", "60天",
            "http://static-csl.9h-sports.com/prop/2016/jiangsusuning.png"),
    BadgeCardHengYuan60("BadgeCardHengYuan60",
            "辽宁宏远", "60天",
            "http://static-csl.9h-sports.com/prop/2016/liaoninghongyuan.png"),
    BadgeCardLvCheng60("BadgeCardLvCheng60",
            "杭州绿城", "60天",
            "http://static-csl.9h-sports.com/prop/2016/lvcheng.png"),
    BadgeCardLuNeng60("BadgeCardLuNeng60",
            "山东鲁能", "60天",
            "http://static-csl.9h-sports.com/prop/2016/shandongluneng.png"),
    BadgeCardShangGang60("BadgeCardShangGang60",
            "上海上港", "60天",
            "http://static-csl.9h-sports.com/prop/2016/shanggang.png"),
    BadgeCardTaiDa60("BadgeCardTaiDa60",
            "天津泰达", "60天",
            "http://static-csl.9h-sports.com/prop/2016/taida.png"),
    BadgeCardYaTai60("BadgeCardYaTai60",
            "长春亚泰", "60天",
            "http://static-csl.9h-sports.com/prop/2016/yatai.png"),
    BadgeCardYanBian60("BadgeCardYanBian60",
            "延边长白山", "60天",
            "http://static-csl.9h-sports.com/prop/2016/yanbian.png"),
    BadgeCardYongChang60("BadgeCardYongChang60",
            "石家庄永昌", "60天",
            "http://static-csl.9h-sports.com/prop/2016/yongchang.png"),

}